name: Sincronizar Pipz com Google Cloud

on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4 # Atualizado

      - name: Instalar Python
        uses: actions/setup-python@v5 # Atualizado
        with:
          python-version: '3.11'

      - name: Instalar Dependências
        run: |
          pip install requests pandas sqlalchemy psycopg2-binary

      - name: Executar Script
        env:
          PIPZ_TOKEN: ${{ secrets.PIPZ_TOKEN }}
          DB_URL: ${{ secrets.DB_URL }}
        run: python main.py