name: Sincronizar Pipz com Google Cloud

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Autenticar no Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Baixar e Iniciar Cloud SQL Proxy
        run: |
          curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.11.0/cloud-sql-proxy.linux.amd64
          chmod +x cloud-sql-proxy
          # Inicia o proxy em segundo plano
          ./cloud-sql-proxy "caldeira-lake:southamerica-east1:banco-de-dados-caldeira-campus" & 
          # Aguarda 5 segundos para o túnel estabilizar
          sleep 5

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Dependencias
        run: pip install requests pandas sqlalchemy pg8000 psycopg2-binary

      - name: Executar Script
        env:
          PIPZ_TOKEN: ${{ secrets.PIPZ_TOKEN }}
          PIPZ_SECRET: ${{ secrets.PIPZ_SECRET }}
          DB_URL: ${{ secrets.DB_URL }}
        run: python main.py