name: Sincronizar Pipz com Google Cloud

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Autenticar no Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Iniciar Cloud SQL Proxy
        # Mudamos de @v2 para @v1 (esta é a versão correta existente)
        uses: google-github-actions/setup-cloudsql-connect@v1 
        with:
          instance_connection_name: "caldeira-lake:southamerica-east1:banco-de-dados-caldeira-campus"

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Dependências
        run: pip install requests pandas sqlalchemy pg8000 psycopg2-binary

      - name: Executar Script
        env:
          PIPZ_TOKEN: ${{ secrets.PIPZ_TOKEN }}
          DB_URL: ${{ secrets.DB_URL }}
        run: python main.py